CREATE TABLE Board(
   number		BIGINT			PRIMARY KEY AUTO_INCREMENT,
   title		VARCHAR(100)	NOT NULL,
   content		VARCHAR(150)	NOT NULL,
   likecount	INT				DEFAULT 0,
   regDate		TIMESTAMP		DEFAULT CURRENT_TIMESTAMP,
   imgname		VARCHAR(100)	DEFAULT NULL
);
   CONSTRAINT Board_userId_FK FOREIGN KEY (userId) REFERENCES User(userId)

SELECT * FROM Board;

DROP TABLE Board;