CREATE TABLE shop (
	BUSINESS_NUMBER		VARCHAR(13) 	PRIMARY KEY,
	SHOP_NAME 			VARCHAR(50) 	NOT NULL,
	SHOP_TEL			VARCHAR(12)		NOT NULL,
	SHOP_ADDRESS		VARCHAR(50)		NOT NULL,
	SHOP_HOURS			VARCHAR(8)		NOT NULL,
	SHOP_IMG			VARCHAR(10)		NOT NULL DEFAULT 'default',
);

CREATE TABLE menu (
	SHOP_NAME_FK		VARCHAR(50)		NOT NULL,
	SHOP_MENU_NAME		VARCHAR(20)		NOT NULL DEFAULT '-',
	SHOP_MENU_INTRO		VARCHAR(30)		NOT NULL DEFAULT '-',
	SHOP_MENU_PRICE		INT(6)			NOT NULL DEFAULT 0,
	SHOP_MENU_IMG		VARCHAR(10)		NOT NULL DEFAULT 'default'
);

SELECT * shop;

DELETE FROM SHOP;