/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2022-08-23 04:48:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class update_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1656316243398L));
    _jspx_dependants.put("jar:file:/C:/wgt/Where-are-you-going-today/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/wgt/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\" xmlns:th=\"http://www.thymeleaf.org\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=no,  maximum-scale=1.0, minimum-scale=1.0\">\r\n");
      out.write("<title>게시판 - 글 수정</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=no,  maximum-scale=1.0, minimum-scale=1.0\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../resources/board/write.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../resources/board/home.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Lobster&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.15.4/css/all.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<header class=\"headerContainer\">\r\n");
      out.write("		<!--상단 탭 만들기 뼈대구조-->\r\n");
      out.write("		<form action=\"home\" method=\"post\">\r\n");
      out.write("			<div class=\"headerContents\">\r\n");
      out.write("				<!--상단 탭 내용물 감싼구조-->\r\n");
      out.write("				<div class=\"WestagramTag\">\r\n");
      out.write("					<!--상단 좌측 내용물-->\r\n");
      out.write("					<a href=\"home\"><i class=\"fab fa-instagram\"></i> | <span>Wgt</span>agram</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"headerSearchBar\" style=\"border-radius: 5px;\">\r\n");
      out.write("					<!--상단 중앙 내용물-->\r\n");
      out.write("					<i class=\"fas fa-search\"></i> <input name=\"title\" type=\"text\"\r\n");
      out.write("						placeholder=\" 게시글 검색\" style=\"border: none; outline: none;\"> <input\r\n");
      out.write("						type=\"submit\" value=\"검색\" style=\"display: none;\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("	</header>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"mypage\">\r\n");
      out.write("		<a href=\"mypage\"><img id=\"user\"\r\n");
      out.write("			src=\"../resources/board/img/user.png\" width=\"30px\" height=\"30px\"\r\n");
      out.write("			style=\"cursor: pointer;\"></a>\r\n");
      out.write("	</div>\r\n");
      out.write("	<h3 style=\"text-align: center; margin-top: 30px; margin-bottom: -15px;\">게시글 수정</h3>\r\n");
      out.write("	<div class=\"write_area\">\r\n");
      out.write("		<form action=\"update\" method=\"post\" enctype=\"multipart/form-data\"\r\n");
      out.write("			style=\"text-align: center; display: grid; justify-content: center; margin-top: 40px;\">\r\n");
      out.write("			<input class=\"update\" name=\"number\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.number}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"display:none;\">\r\n");
      out.write("			<span>제목</span>\r\n");
      out.write("			<textarea class=\"title_area\" name=\"title\"\r\n");
      out.write("				maxlength=\"50\" required>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea><!-- input은 <>안에, textarea는 <>밖에 -->\r\n");
      out.write("			<span>내용</span>\r\n");
      out.write("			<textarea class=\"content_area\" name=\"content\"\r\n");
      out.write("				maxlength=\"150\" required>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("			사진 선택 : <span><input type=\"file\" accept=\".jpg\" name=\"file\"><br></span>\r\n");
      out.write("					<br><img id=\"profileImg\" src=\"../resources/board/img/upload/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.imgname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".jpg\" style=\"width:50px; height:50px; margin:0 auto;\">이미지\r\n");
      out.write("				<input type=\"submit\" class=\"update\" value=\"수정하기\" required=\"required\"><br>\r\n");
      out.write("		</form>\r\n");
      out.write("		<button class=\"go_home\" onclick=\"location.href='mypage'\">목록으로</button>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	\r\n");
      out.write("		// 이미지 파일 수정\r\n");
      out.write("		// input 태그 (name이 file)를 가져옴 \r\n");
      out.write("		let fileTag = document.querySelector(\"input[name=file]\");\r\n");
      out.write("		\r\n");
      out.write("		// 파일태그에 변화가 있을 때 실행될 함수 작성 \r\n");
      out.write("		fileTag.onchange = function () {\r\n");
      out.write("			\r\n");
      out.write("			let imgTag = document.querySelector(\"#profileImg\");\r\n");
      out.write("			\r\n");
      out.write("			// 파일이 있는지 확인\r\n");
      out.write("			if(fileTag.files.length > 0) {\r\n");
      out.write("				// 파일을 선택한 경우 미리보기 생성 (이미지 태그 src에 데이터를 넣어주면 됨)\r\n");
      out.write("				let reader = new FileReader();\r\n");
      out.write("				\r\n");
      out.write("				// reader 읽어들이는 작업(onload)를 끝냈을 때 함수 실행, 읽어온 데이터를 함수의 파라미터로 줄 수 있음\r\n");
      out.write("				reader.onload = function (data) {\r\n");
      out.write("					console.log(data);\r\n");
      out.write("					imgTag.src = data.target.result;\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("				reader.readAsDataURL(fileTag.files[0]);\r\n");
      out.write("			} else {\r\n");
      out.write("				// 취소 버튼 누를 경우\r\n");
      out.write("				imgTag.src = \"\";\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("		</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
